// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipFleet.Infrastructure.Data;

#nullable disable

namespace ShipFleet.Infrastructure.Migrations
{
    [DbContext(typeof(ShipFleetDbContext))]
    partial class ShipFleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShipFleet.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrivalPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CargoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CargoWeightMT")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeparturePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PlannedArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId");

                    b.HasIndex("ArrivalPortId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("RequesterId");

                    b.HasIndex("ShipId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Captain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LicenseExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Captains");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.CaptainAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaptainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId");

                    b.HasIndex("ShipId");

                    b.ToTable("CaptainAssignments");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.FuelLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostPerMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoggedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("NauticalMilesAtBunkering")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("PortOfBunkering")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QuantityMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoggedByUserId");

                    b.HasIndex("ShipId");

                    b.ToTable("FuelLogs");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.LoginAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("Email");

                    b.ToTable("LoginAttempts");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.MaintenanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LoggedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("NauticalMilesAtService")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime?>("NextServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortOfMaintenance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LoggedByUserId");

                    b.HasIndex("ShipId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            City = "Shanghai",
                            Code = "CNSHA",
                            Country = "China",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 31.2304m,
                            Longitude = 121.4737m,
                            Name = "Port of Shanghai"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            City = "Singapore",
                            Code = "SGSIN",
                            Country = "Singapore",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 1.2966m,
                            Longitude = 103.8006m,
                            Name = "Port of Singapore"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            City = "Rotterdam",
                            Code = "NLRTM",
                            Country = "Netherlands",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 51.9225m,
                            Longitude = 4.4792m,
                            Name = "Port of Rotterdam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            City = "Dubai",
                            Code = "AEDXB",
                            Country = "UAE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 25.2048m,
                            Longitude = 55.2708m,
                            Name = "Port of Dubai"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            City = "Karachi",
                            Code = "PKPQI",
                            Country = "Pakistan",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 24.7925m,
                            Longitude = 67.3218m,
                            Name = "Port Qasim"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            City = "Los Angeles",
                            Code = "USLAX",
                            Country = "USA",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 33.7287m,
                            Longitude = -118.2620m,
                            Name = "Port of Los Angeles"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            City = "Hamburg",
                            Code = "DEHAM",
                            Country = "Germany",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 53.5753m,
                            Longitude = 10.0153m,
                            Name = "Port of Hamburg"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            City = "Colombo",
                            Code = "LKCMB",
                            Country = "Sri Lanka",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Latitude = 6.9271m,
                            Longitude = 79.8612m,
                            Name = "Port of Colombo"
                        });
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Ship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Beam")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CurrentHeading")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("CurrentLatitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("CurrentLongitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("CurrentSpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("DeadweightTonnage")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Draft")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FuelCapacityMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("GrossTonnage")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastPositionUpdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LengthOverall")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("MaxSpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NauticalMilesTravelled")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryFuelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.ToTable("Ships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            Beam = 45m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 22.3m,
                            CurrentLongitude = 114.1m,
                            DeadweightTonnage = 95000m,
                            Draft = 14m,
                            Flag = "Panama",
                            FuelCapacityMT = 3000m,
                            GrossTonnage = 85000m,
                            ImoNumber = "IMO9234567",
                            IsDeleted = false,
                            LengthOverall = 300m,
                            MaxSpeedKnots = 22m,
                            Name = "MV Pacific Star",
                            NauticalMilesTravelled = 125000m,
                            PrimaryFuelType = "VLSFO",
                            Status = "UnderWay",
                            Type = "ContainerShip",
                            YearBuilt = 2018
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            Beam = 32m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 51.9m,
                            CurrentLongitude = 4.4m,
                            DeadweightTonnage = 75000m,
                            Draft = 12m,
                            Flag = "Liberia",
                            FuelCapacityMT = 2000m,
                            GrossTonnage = 45000m,
                            ImoNumber = "IMO9345678",
                            IsDeleted = false,
                            LengthOverall = 225m,
                            MaxSpeedKnots = 14m,
                            Name = "MV Atlantic Horizon",
                            NauticalMilesTravelled = 98000m,
                            PrimaryFuelType = "HFO",
                            Status = "InPort",
                            Type = "BulkCarrier",
                            YearBuilt = 2016
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            Beam = 44m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 12.5m,
                            CurrentLongitude = 65.3m,
                            DeadweightTonnage = 110000m,
                            Draft = 15m,
                            Flag = "Marshall Islands",
                            FuelCapacityMT = 2500m,
                            GrossTonnage = 60000m,
                            ImoNumber = "IMO9456789",
                            IsDeleted = false,
                            LengthOverall = 250m,
                            MaxSpeedKnots = 15m,
                            Name = "MV Indian Ocean",
                            NauticalMilesTravelled = 75000m,
                            PrimaryFuelType = "MGO",
                            Status = "UnderWay",
                            Type = "Tanker",
                            YearBuilt = 2019
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            Beam = 30m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 25.2m,
                            CurrentLongitude = 55.2m,
                            DeadweightTonnage = 55000m,
                            Draft = 11m,
                            Flag = "UAE",
                            FuelCapacityMT = 1500m,
                            GrossTonnage = 35000m,
                            ImoNumber = "IMO9567890",
                            IsDeleted = false,
                            LengthOverall = 200m,
                            MaxSpeedKnots = 18m,
                            Name = "MV Arabian Gulf",
                            NauticalMilesTravelled = 45000m,
                            PrimaryFuelType = "VLSFO",
                            Status = "InPort",
                            Type = "CargoVessel",
                            YearBuilt = 2020
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            Beam = 28m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 55.6m,
                            CurrentLongitude = 12.5m,
                            DeadweightTonnage = 42000m,
                            Draft = 10m,
                            Flag = "Norway",
                            FuelCapacityMT = 1200m,
                            GrossTonnage = 28000m,
                            ImoNumber = "IMO9678901",
                            IsDeleted = false,
                            LengthOverall = 185m,
                            MaxSpeedKnots = 16m,
                            Name = "MV Baltic Pioneer",
                            NauticalMilesTravelled = 62000m,
                            PrimaryFuelType = "MGO",
                            Status = "Anchored",
                            Type = "GeneralCargo",
                            YearBuilt = 2017
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            Beam = 35m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 36.8m,
                            CurrentLongitude = 22.4m,
                            DeadweightTonnage = 58000m,
                            Draft = 11m,
                            Flag = "Greece",
                            FuelCapacityMT = 1800m,
                            GrossTonnage = 42000m,
                            ImoNumber = "IMO9789012",
                            IsDeleted = false,
                            LengthOverall = 210m,
                            MaxSpeedKnots = 20m,
                            Name = "MV Mediterranean Express",
                            NauticalMilesTravelled = 28000m,
                            PrimaryFuelType = "LNG",
                            Status = "UnderWay",
                            Type = "RoRo",
                            YearBuilt = 2021
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            Beam = 26m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 24.7m,
                            CurrentLongitude = 67.3m,
                            DeadweightTonnage = 35000m,
                            Draft = 9m,
                            Flag = "Pakistan",
                            FuelCapacityMT = 900m,
                            GrossTonnage = 22000m,
                            ImoNumber = "IMO9890123",
                            IsDeleted = false,
                            LengthOverall = 170m,
                            MaxSpeedKnots = 14m,
                            Name = "MV Karachi Trader",
                            NauticalMilesTravelled = 88000m,
                            PrimaryFuelType = "HFO",
                            Status = "InPort",
                            Type = "CargoVessel",
                            YearBuilt = 2015
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            Beam = 48m,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentLatitude = 1.3m,
                            CurrentLongitude = 103.8m,
                            DeadweightTonnage = 115000m,
                            Draft = 16m,
                            Flag = "Singapore",
                            FuelCapacityMT = 4000m,
                            GrossTonnage = 95000m,
                            ImoNumber = "IMO9901234",
                            IsDeleted = false,
                            LengthOverall = 340m,
                            MaxSpeedKnots = 24m,
                            Name = "MV Pearl of Asia",
                            NauticalMilesTravelled = 18000m,
                            PrimaryFuelType = "LNG",
                            Status = "UnderWay",
                            Type = "ContainerShip",
                            YearBuilt = 2022
                        });
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.ShipLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HeadingDegrees")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SpeedKnots")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipLocations");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@shipfleet.com",
                            FullName = "System Admin",
                            IsActive = true,
                            IsApproved = false,
                            IsDeleted = false,
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Voyage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ArrivalPortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaptainId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CargoDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CargoWeightMT")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeparturePortId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DistanceNauticalMiles")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("FuelConsumedMT")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PlannedArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PlannedDeparture")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoyageNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalPortId");

                    b.HasIndex("BookingRequestId")
                        .IsUnique()
                        .HasFilter("[BookingRequestId] IS NOT NULL");

                    b.HasIndex("CaptainId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("ShipId");

                    b.ToTable("Voyages");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.VoyageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoggedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LoggedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ShipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("VoyageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("VoyageLogs", (string)null);
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.BookingRequest", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.User", "Approver")
                        .WithMany("ApprovedRequests")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShipFleet.Core.Entities.Port", "ArrivalPort")
                        .WithMany("ArrivalBookings")
                        .HasForeignKey("ArrivalPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.Port", "DeparturePort")
                        .WithMany("DepartureBookings")
                        .HasForeignKey("DeparturePortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.User", "Requester")
                        .WithMany("BookingRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("BookingRequests")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("ArrivalPort");

                    b.Navigation("DeparturePort");

                    b.Navigation("Requester");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Captain", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.User", "User")
                        .WithOne("Captain")
                        .HasForeignKey("ShipFleet.Core.Entities.Captain", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.CaptainAssignment", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.Captain", "Captain")
                        .WithMany("Assignments")
                        .HasForeignKey("CaptainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("CaptainAssignments")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Captain");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.FuelLog", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.User", "LoggedBy")
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("FuelLogs")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoggedBy");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.User", "LoggedBy")
                        .WithMany()
                        .HasForeignKey("LoggedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LoggedBy");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.ShipLocation", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("LocationHistory")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Voyage", b =>
                {
                    b.HasOne("ShipFleet.Core.Entities.Port", "ArrivalPort")
                        .WithMany("ArrivalVoyages")
                        .HasForeignKey("ArrivalPortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.BookingRequest", "BookingRequest")
                        .WithOne("Voyage")
                        .HasForeignKey("ShipFleet.Core.Entities.Voyage", "BookingRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShipFleet.Core.Entities.Captain", "Captain")
                        .WithMany("Voyages")
                        .HasForeignKey("CaptainId");

                    b.HasOne("ShipFleet.Core.Entities.Port", "DeparturePort")
                        .WithMany("DepartureVoyages")
                        .HasForeignKey("DeparturePortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ShipFleet.Core.Entities.Ship", "Ship")
                        .WithMany("Voyages")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalPort");

                    b.Navigation("BookingRequest");

                    b.Navigation("Captain");

                    b.Navigation("DeparturePort");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.BookingRequest", b =>
                {
                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Captain", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Port", b =>
                {
                    b.Navigation("ArrivalBookings");

                    b.Navigation("ArrivalVoyages");

                    b.Navigation("DepartureBookings");

                    b.Navigation("DepartureVoyages");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.Ship", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("CaptainAssignments");

                    b.Navigation("FuelLogs");

                    b.Navigation("LocationHistory");

                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("ShipFleet.Core.Entities.User", b =>
                {
                    b.Navigation("ApprovedRequests");

                    b.Navigation("BookingRequests");

                    b.Navigation("Captain");
                });
#pragma warning restore 612, 618
        }
    }
}
